### ISSUE TITLE
Failure to use read_parquet_into_pyarrow with on-prem Ceph cluster

### ISSUE THREAD

**Issue by marsupialtail** [Eventual-Inc/Daft#1393]
It seems like the read_parquet_into_pyarrow does not support on-premise Ceph setups. Did you guys test with something like MinIO? It looks like read_parquet also doesn't quite work. I suspect there's some hiccups in endpoint overriding logic.

>>> s3_config = daft.io.S3Config(endpoint_url = "https://ceph.XXX/", key_id = "XXX", access_key = "XXX")
>>> io_config = daft.io.IOConfig(s3 = s3_config)
>>> daft.table.read_parquet_into_pyarrow("s3://XXX/", io_config = io_config,  multithreaded_io = True)
2023-09-20 09:47:10.875 | WARNING  | logging:handle:1599 - unrecognized error from Hyper. If this error should be retried, please file an issue. err=error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (hostname mismatch): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (hostname mismatch): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1889 }]))) }, X509VerifyResult { code: 62, error: "hostname mismatch" })))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tony/miniconda3/envs/dataviz/lib/python3.9/site-packages/daft/table/table.py", line 466, in read_parquet_into_pyarrow
    fields, metadata, columns = _read_parquet_into_pyarrow(
ValueError: DaftError::External Unhandled Error for path: s3://XXX/
Details:
unhandled error: dispatch failure: other: error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (hostname mismatch): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (hostname mismatch): error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (Unhandled { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1889 }]))) }, X509VerifyResult { code: 62, error: "hostname mismatch" })), connection: Unknown } }), meta: ErrorMetadata { code: None, message: None, extras: None } })

**Comment by jaychia** [comment]
cc @samster25 who has more context on TLS

**Comment by jaychia** [comment]
Fixed merged in: https://github.com/Eventual-Inc/Daft/pull/1395

@marsupialtail please feel free to update the issue once/if you can verify the fix!
