### ISSUE TITLE
Cannot add column from series to concatenated data frame

### ISSUE THREAD

**Issue by hanslovsky** [Eventual-Inc/Daft#1992]
**Describe the bug**
I use daft `0.2.17` on macOS and would like to add a column from a series with the appropriate length to a concatenated data frame. When I collect the data frame, I see a `DaftError::ValueError`. It works properly if I use a single dataframe without concatenating.

**To Reproduce**
This Python script
```python
import daft
import numpy as np

df = daft.from_pydict(dict(a=list("abcd"), b=list(range(4))))
print(df)

df = df.concat(df)
print(df.collect())

df_idx = df.with_column("_index", daft.lit(daft.Series.from_numpy(np.arange(df.count_rows()))))
print(df_idx.collect())
```
produces this output, including the error:
```
╭──────┬───────╮
│ a    ┆ b     │
│ ---  ┆ ---   │
│ Utf8 ┆ Int64 │
╞══════╪═══════╡
│ a    ┆ 0     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ b    ┆ 1     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c    ┆ 2     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ d    ┆ 3     │
╰──────┴───────╯

(Showing first 4 of 4 rows)
╭──────┬───────╮
│ a    ┆ b     │
│ ---  ┆ ---   │
│ Utf8 ┆ Int64 │
╞══════╪═══════╡
│ a    ┆ 0     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ b    ┆ 1     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c    ┆ 2     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ d    ┆ 3     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ a    ┆ 0     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ b    ┆ 1     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c    ┆ 2     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ d    ┆ 3     │
╰──────┴───────╯

(Showing first 8 of 8 rows)
Project [Stage:4]:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "workspace/map-lib-backend/daft-bug.py", line 11, in <module>                  
    print(df_idx.collect())
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/api_annotations.py", line 31, in _wrap
    return timed_method(*args, **kwargs)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/analytics.py", line 189, in tracked_method
    result = method(*args, **kwargs)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/dataframe/dataframe.py", line 1126, in collect
    self._materialize_results()
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/dataframe/dataframe.py", line 1108, in _materialize_results
    self._result_cache = context.runner().run(self._builder)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/runners/pyrunner.py", line 123, in run
    results = list(self.run_iter(builder))
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/runners/pyrunner.py", line 151, in run_iter
    yield from results_gen
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/runners/pyrunner.py", line 238, in _physical_plan_to_partitions
    partitions = done_future.result()
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/runners/pyrunner.py", line 280, in build_partitions
    partitions = instruction.run(partitions)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/execution/execution_step.py", line 401, in run
    return self._project(inputs)
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/execution/execution_step.py", line 405, in _project
    return [input.eval_expression_list(self.projection)]
  File "mambaforge/envs/backend-benchmarks/lib/python3.10/site-packages/daft/table/micropartition.py", line 169, in eval_expression_list
    return MicroPartition._from_pymicropartition(self._micropartition.eval_expression_list(pyexprs))
ValueError: DaftError::ValueError While building a Table, we found that the Series lengths did not match. Series named: _index had length: 8 vs rest of the DataFrame had length: 4
```

**Expected behavior**
Return the collected dataframe with the series.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 0.2.17

**Comment by hanslovsky** [comment]
FYI, without concatenating,
```python
import daft
import numpy as np

df = daft.from_pydict(dict(a=list("abcd"), b=list(range(4))))
print(df)

df_idx = df.with_column("_index", daft.lit(daft.Series.from_numpy(np.arange(df.count_rows()))))
print(df_idx.collect())
```
this works as expected:
```
╭──────┬───────╮
│ a    ┆ b     │
│ ---  ┆ ---   │
│ Utf8 ┆ Int64 │
╞══════╪═══════╡
│ a    ┆ 0     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ b    ┆ 1     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ c    ┆ 2     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┤
│ d    ┆ 3     │
╰──────┴───────╯

(Showing first 4 of 4 rows)
╭──────┬───────┬────────╮                                                 
│ a    ┆ b     ┆ _index │
│ ---  ┆ ---   ┆ ---    │
│ Utf8 ┆ Int64 ┆ Int64  │
╞══════╪═══════╪════════╡
│ a    ┆ 0     ┆ 0      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ b    ┆ 1     ┆ 1      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ c    ┆ 2     ┆ 2      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ d    ┆ 3     ┆ 3      │
╰──────┴───────┴────────╯

(Showing first 4 of 4 rows)
```

**Comment by jaychia** [comment]
Hi @hanslovsky

Thanks for making this issue!

I'll check in with the rest of the team, but the `df = df.with_column("foo", lit(...))` API is actually meant to "broadcast" the lit, rather than concatenate it with the dataframe. This could be a bug and unintended behavior that allows it to concatenate in your second example.

In fact, this is what I would expect as output:

```
╭──────┬───────┬────────────────╮                                                 
│ a    ┆ b     ┆ _index         │
│ ---  ┆ ---   ┆ ---            │
│ Utf8 ┆ Int64 ┆ list[int64]    │
╞══════╪═══════╪════════════════╡
│ a    ┆ 0     ┆ [0,1,2,3]      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 1     ┆ [0,1,2,3]      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ c    ┆ 2     ┆ [0,1,2,3]      │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ d    ┆ 3     ┆ [0,1,2,3]      │
╰──────┴───────┴────────────────╯
```

It seems that what you're looking for instead if either:

1. We can add a `row_number()` expression to populate each row with the row number: `df = df.with_column("index", daft.row_number())`
2. We can add a "hcat" concatenation:

```python
df = ...
index_df = daft.from_pydict("index", range(0, df.count_rows()))

# Repartitions the dataframes to be the same partitioning, and then hcats each partition
df.hcat(index_df)
```

Let me know what you think!

**Comment by hanslovsky** [comment]
Thank you for the prompt response @jaychia!

You are correct, that `row_number()` would probably be the solution that I am looking for. Regarding
> API is actually meant to "broadcast" the lit, rather than concatenate it with the dataframe. This could be a bug and unintended behavior that allows it to concatenate in your second example.

It sounds very much like a bug for me. For instance, if I pass the `np.ndarray` directly without `Series.from_numpy`, I get this output:
```
╭──────┬───────┬───────────╮                                                                                
│ a    ┆ b     ┆ _index    │
│ ---  ┆ ---   ┆ ---       │
│ Utf8 ┆ Int64 ┆ Python    │
╞══════╪═══════╪═══════════╡
│ a    ┆ 0     ┆ [0 1 2 3] │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ b    ┆ 1     ┆ [0 1 2 3] │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ c    ┆ 2     ┆ [0 1 2 3] │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ d    ┆ 3     ┆ [0 1 2 3] │
╰──────┴───────┴───────────╯

(Showing first 4 of 4 rows)
```
which is what you expected.

For some more context, I am trying to [z-score](https://en.wikipedia.org/wiki/Standard_score) my data by groups. For now, I am basically just subtracting the group-based mean of each row. I can do this with groupby, aggregation, and join, but only `inner` join is currently supported and the original order of the data is not preserved.
```python
import daft
import numpy as np

df = daft.from_pydict(dict(
    a=np.mod(np.arange(8), 3),
    b=np.random.random(8)
))
print(df)

zscored = df.join(df.groupby("a").mean("b"), on="a", how="inner").select(daft.col("a"), daft.col("b") - daft.col("right.b"))

print(zscored.collect())
```
Output:
```
╭───────┬─────────────────────╮
│ a     ┆ b                   │
│ ---   ┆ ---                 │
│ Int64 ┆ Float64             │
╞═══════╪═════════════════════╡
│ 0     ┆ 0.6716204504722777  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.3698519886785866  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 0.9613092524546862  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.17581968456449115 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.37594559666987937 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 0.25923763363184327 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.4698116468157315  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.6560295370040454  │
╰───────┴─────────────────────╯

(Showing first 8 of 8 rows)
╭───────┬──────────────────────╮                                                                            
│ a     ┆ b                    │                                                                            
│ ---   ┆ ---                  │
│ Int64 ┆ Float64              │
╞═══════╪══════════════════════╡
│ 2     ┆ 0.35103580941142143  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ -0.35103580941142154 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ -0.09742371877225053 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ -0.09133011078095776 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.1887538295532083   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.23253652318811097  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ -0.2632642427196756  │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.03072771953156478  │
╰───────┴──────────────────────╯

(Showing first 8 of 8 rows)
```
I try to fix this by adding the index/row number and sort by that afterwards. I figure this would also be solved by a `left` join because this would probably preserve order of the left dataframe. We have thousands to tens of thousands of columns, so I don't know how efficient the `daft.col("b") - daft.col("right.b")` part will be on full data.

We are currently evaluating data backends to move away from pandas and we had picked modin after some benchmarking. A co-worker just brought up daft and I want to look into it to see if we can express our transformations in daft and benchmark against modin for our use case.

**Comment by hanslovsky** [comment]
I believe I was able to solve `row_number` with a `udf` (this also includes median aggregation of groups):
```python
wimport daft
import numpy as np

@daft.udf(return_dtype=daft.DataType.float64())
def median(x: daft.Series):
    return [float(np.median(x.to_pylist()))]

@daft.udf(return_dtype=daft.DataType.uint64())
def row_number(x: daft.Series):
    return list(range(len(x)))

df = daft.from_pydict(dict(
    a=np.mod(np.arange(8), 3),
    b=np.random.random(8)
))
print(df)

# agg = df.groupby("a").mean("b")
agg = df.groupby("a").map_groups(median(df["b"]))
df_idx = df.with_column("_index", row_number(df["a"]))
zscored = df_idx.join(agg, on="a", how="inner").sort("_index").select(daft.col("_index",), daft.col("a"), daft.col("b") - daft.col("right.b"))

print(zscored.collect())
```

with output
```
╭───────┬──────────────────────╮
│ a     ┆ b                    │
│ ---   ┆ ---                  │
│ Int64 ┆ Float64              │
╞═══════╪══════════════════════╡
│ 0     ┆ 0.012102950612597141 │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.5763995541141047   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 0.8071136945169707   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.973689486804222    │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.7279032494926901   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2     ┆ 0.6091056319134921   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0     ┆ 0.8966416295463971   │
├╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1     ┆ 0.7553185827534598   │
╰───────┴──────────────────────╯

(Showing first 8 of 8 rows)
╭────────┬───────┬──────────────────────╮                                                                                                                                                                                                            
│ _index ┆ a     ┆ b                    │                                                                                                                                                                                                            
│ ---    ┆ ---   ┆ ---                  │                                                                                                                                                                                                            
│ UInt64 ┆ Int64 ┆ Float64              │                                                                                                                                                                                                            
╞════════╪═══════╪══════════════════════╡                                                                                                                                                                                                            
│ 0      ┆ 0     ┆ -0.8845386789338     │                                                                                                                                                                                                            
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1      ┆ 1     ┆ -0.15150369537858543 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 2      ┆ 2     ┆ 0.09900403130173929  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 3      ┆ 0     ┆ 0.07704785725782481  │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 4      ┆ 1     ┆ 0                    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 5      ┆ 2     ┆ -0.09900403130173929 │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 6      ┆ 0     ┆ 0                    │
├╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 7      ┆ 1     ┆ 0.027415333260769614 │
╰────────┴───────┴──────────────────────╯

(Showing first 8 of 8 rows)
```

I will also have to try with median over multiple columns.

**Comment by jaychia** [comment]
Thanks for all the elaboration! If I understand correctly: You need `row_number()` functionality because you would like to maintain ordering of the dataframe after the inner join

You can actually try to achieve this using a sort-merge join :)

```
df = df.join(df_agged, on="a", strategy="sort_merge")
```

**Comment by jaychia** [comment]
Oh actually I thought about it a bit more… the sort_merge join strategy will have results sorted by the join key, but not the original row_number. 

In the meantime to unblock yourself, take a look at our `df._add_monotonically_increasing_id(“_index”)` API

Let me check in with the team to see if they have any thoughts here.

**Comment by hanslovsky** [comment]
I just tried `df._add_monotonically_increasing_id(“_index”)` and that works for me. Thank you for the support!

**Comment by jaychia** [comment]
> I just tried `df._add_monotonically_increasing_id(“_index”)` and that works for me. Thank you for the support!

Awesome! Glad this helped.

We'll take a look at the bug that you found with `lit(Series)` as well!
