### ISSUE TITLE
daft.exceptions.ByteStreamError: Unable to read data from file s3

### ISSUE THREAD

**Issue by alexmi** [Eventual-Inc/Daft#2303]
**Describe the bug**

Following code executes 
df = daft.from_glob_path(
"s3://bucket/*ipname.json.gz"
)
df.collect()
df = df.with_column("data", df["path"].url.download())
df.collect()

and I sometimes get following message (sometimes code works) 

Project [Stage:2]:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/app/output_parquet.py", line 89, in <module>
    df.collect()
  File "/usr/local/lib/python3.9/site-packages/daft/api_annotations.py", line 26, in _wrap
    return timed_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/daft/analytics.py", line 189, in tracked_method
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 1466, in collect
    self._materialize_results()
  File "/usr/local/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 1448, in _materialize_results
root@e7c8865b50f3:/# exit
^Mexit
...skipping...
    self._result_cache = context.runner().run(self._builder)
  File "/usr/local/lib/python3.9/site-packages/daft/runners/pyrunner.py", line 135, in run
    results = list(self.run_iter(builder))
  File "/usr/local/lib/python3.9/site-packages/daft/runners/pyrunner.py", line 187, in run_iter
    yield from results_gen
  File "/usr/local/lib/python3.9/site-packages/daft/runners/pyrunner.py", line 279, in _physical_plan_to_partitions
    materialized_results = done_future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/daft/runners/pyrunner.py", line 325, in build_partitions
    partitions = instruction.run(partitions)
  File "/usr/local/lib/python3.9/site-packages/daft/execution/execution_step.py", line 438, in run
    return self._project(inputs)
  File "/usr/local/lib/python3.9/site-packages/daft/execution/execution_step.py", line 442, in _project
    return [input.eval_expression_list(self.projection)]
  File "/usr/local/lib/python3.9/site-packages/daft/table/micropartition.py", line 169, in eval_expression_list
    return MicroPartition._from_pymicropartition(self._micropartition.eval_expression_list(pyexprs))
daft.exceptions.ByteStreamError: Unable to read data from file s3://bucket/path.json.gz: error reading a body from connection: end of file before message length reached

**To Reproduce**
Execute code to download files from s3 and sometimes error above occurs 

**Expected behavior**
Sometimes the code works and downloads json.gzip data 

**Desktop (please complete the following information):**
Mac Sonoma 14.4.1 (23E224)

**Comment by jaychia** [comment]
Hi @alexmi, thanks for making this issue!

We've seen this happen when Daft is too aggressive with downloading from S3, and S3 starts cutting our connections 🤯 . It sometimes just depends on how well S3 is scaling up to deal with the work that Daft is throwing at it.

Could you give us an idea of how many files you reading?

**Comment by alexmi** [comment]
Hi @jaychia, 
Thank you for your reply.  I have 148 files total match the glob pattern and url.download is applied. Once the files are unzipped and converted to pandas/parquet it saves to one file of 168Mb. 
 Is there a way to specify number of retries similar to boto3 ?
 Thanks

**Comment by jaychia** [comment]
Our [url download docs](https://www.getdaft.io/projects/docs/en/latest/api_docs/doc_gen/expression_methods/daft.Expression.url.download.html) also has some suggestions:

> If you are observing excessive S3 issues (such as timeouts, DNS errors or slowdown errors) during URL downloads, you may wish to reduce the value of max_connections (defaults to 32) to reduce the amount of load you are placing on your S3 servers.

Try this!

```
df["urls"].url.download(max_connections=8)
```

**Comment by alexmi** [comment]
That fixes the problem. My bad to not finding the docs. I'll close this.

**Comment by jaychia** [comment]
Sounds great @alexmi !

I'm also curious - how many cores does your machine have? We're seeing issues around BytesStream interruptions in other I/O code as well.

**Comment by alexmi** [comment]
@jaychia  I was running it on 2.6 Ghz 6-Core Intel Core i7 2019 mac but in a Docker that had 6 CPU setting.  Not sure if it is equal to 6 cores or less.  Perhaps default of max_connections should be tied to number of CPUs.
