### ISSUE TITLE
Casting a List to a FixedSizeList fails when using into_partitions first

### ISSUE THREAD

**Issue by GuyPozner** [Eventual-Inc/Daft#2394]
**Describe the bug**
Casting a List to a FixedSizeList fails when using into_partitions first.

Traceback:
```
Traceback (most recent call last):
  File ".../lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File ".../.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File ".../reproduce_casting_issue.py", line 21, in <module>
    s = next(iter_df)
  File ".../lib/python3.10/site-packages/daft/dataframe/dataframe.py", line 222, in __iter__
    for partition in partitions_iter:
  File ".../lib/python3.10/site-packages/daft/runners/pyrunner.py", line 192, in run_iter_tables
    for result in self.run_iter(builder, results_buffer_size=results_buffer_size):
  File ".../lib/python3.10/site-packages/daft/runners/pyrunner.py", line 187, in run_iter
    yield from results_gen
  File ".../lib/python3.10/site-packages/daft/runners/pyrunner.py", line 279, in _physical_plan_to_partitions
    materialized_results = done_future.result()
  File ".../lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File ".../lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File ".../lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../lib/python3.10/site-packages/daft/runners/pyrunner.py", line 325, in build_partitions
    partitions = instruction.run(partitions)
  File ".../lib/python3.10/site-packages/daft/execution/execution_step.py", line 474, in run
    return self._project(inputs)
  File ".../lib/python3.10/site-packages/daft/execution/execution_step.py", line 478, in _project
    return [input.eval_expression_list(self.projection)]
  File ".../lib/python3.10/site-packages/daft/table/micropartition.py", line 169, in eval_expression_list
    return MicroPartition._from_pymicropartition(self._micropartition.eval_expression_list(pyexprs))
daft.exceptions.DaftCoreException: DaftError::ValueError While building a Table, we found that the Series lengths did not match. Series named: fixed_list had length: 4 vs rest of the DataFrame had length: 2
```

**To Reproduce**

Run the following code:

```python
import daft
import numpy as np
import pandas as pd

N_ROWS = 4
N_ELEMENTS_IN_LIST = 2
N_PARTITIONS = 2

# Create synthetic parquet
num = [i for i in range(N_ROWS)]
fixed_list = [np.random.randint(0, 100, size=N_ELEMENTS_IN_LIST).tolist() for _ in range(N_ROWS)]
df = pd.DataFrame({"fixed_list": fixed_list, "num": num})
df.to_parquet("fixed_list.parquet", engine="pyarrow")

# Read and cast the relevant column
df = daft.read_parquet("fixed_list.parquet").into_partitions(N_PARTITIONS)
dtype = daft.DataType.from_numpy_dtype("int8")
fixed_size_list_dtype = daft.DataType.fixed_size_list(dtype, N_ELEMENTS_IN_LIST)
df = df.with_column("fixed_list", df["fixed_list"].cast(fixed_size_list_dtype))
iter_df = iter(df)
s = next(iter_df)
print(s)
```

**Expected behavior**

print the first sample of the dataframe

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04
 - Daft version: 0.2.27

Thanks

**Comment by samster25** [comment]
@GuyPozner This should now be fixed btw!
