### ISSUE TITLE
Error: Schema and number of arrays unequal when reading from hudi table

### ISSUE THREAD

**Issue by hsduan** [Eventual-Inc/Daft#2569]
**Describe the bug**
I was trying to use daft to query a hudi-based lakehouse. An example is shown below. It can print the schema successfully but it'd fail when converting to pandas dataframe with an error message: **ValueError: Schema and number of arrays unequal**. I did some research on the internet but haven't found anything useful yet. Data is partitioned by year and month. According to @jaychia, this may have to do with `pyhudi` implementation.. 

cc: @xushiyan 

```
import daft
import boto3

bucket_path = "s3://my-bucket/sandbox/daft_hudi"

def main():
    session = boto3.session.Session()
    creds = session.get_credentials()
    io_config = daft.io.IOConfig(
        s3=daft.io.S3Config(
            access_key=creds.secret_key,
            key_id=creds.access_key,
            session_token=creds.token,
            region_name="us-east-1",
        )
    )
    df = daft.read_hudi(bucket_path, io_config=io_config).select('year', 'month', 'day')    
    print(df.schema())
    df_pandas = df.to_pandas()

if __name__ == "__main__":
    main()
```

Full trackback
```
Traceback (most recent call last):
 File "path\test_daft.py", line 22, in <module>
   main()
 File "path\test_daft.py", line 19, in main
   df_pandas = df.to_pandas()
 File "Path\myenv\lib\site-packages\daft\api_annotations.py", line 26, in _wrap
   return timed_method(*args, **kwargs)
 File "Path\myenv\lib\site-packages\daft\analytics.py", line 189, in tracked_method
   result = method(*args, **kwargs)
 File "Path\myenv\lib\site-packages\daft\dataframe\dataframe.py", line 2193, in to_pandas
   self.collect()
 File "Path\myenv\lib\site-packages\daft\api_annotations.py", line 26, in _wrap
   return timed_method(*args, **kwargs)
 File "Path\myenv\lib\site-packages\daft\analytics.py", line 189, in tracked_method
   result = method(*args, **kwargs)
 File "Path\myenv\lib\site-packages\daft\dataframe\dataframe.py", line 2060, in collect
   self._materialize_results()
 File "Path\myenv\lib\site-packages\daft\dataframe\dataframe.py", line 2042, in _materialize_results
   self._result_cache = context.runner().run(self._builder)
 File "Path\myenv\lib\site-packages\daft\runners\pyrunner.py", line 143, in run
   results = list(self.run_iter(builder))
 File "Path\myenv\lib\site-packages\daft\runners\pyrunner.py", line 204, in run_iter
   plan_scheduler = [builder.to](http://builder.to/)_physical_plan_scheduler(daft_execution_config)
 File "Path\myenv\lib\site-packages\daft\logical\builder.py", line 47, in to_physical_plan_scheduler
   return PhysicalPlanScheduler.from_logical_plan_builder(
 File "Path\myenv\lib\site-packages\daft\plan_scheduler\physical_plan_scheduler.py", line 35, in from_logical_plan_builder
   scheduler = _PhysicalPlanScheduler.from_logical_plan_builder(builder._builder, daft_execution_config)
 File "Path\myenv\lib\site-packages\daft\hudi\hudi_scan.py", line 54, in to_scan_tasks
   hudi_table_metadata: HudiTableMetadata = self._table.latest_table_metadata()
 File "Path\myenv\lib\site-packages\daft\hudi\pyhudi\table.py", line 186, in latest_table_metadata
   pa.RecordBatch.from_arrays(min_value_arrays, schema=colstats_schema),
 File "pyarrow\\table.pxi", line 3429, in pyarrow.lib.RecordBatch.from_arrays
 File "pyarrow\\table.pxi", line 1557, in pyarrow.lib._sanitize_arrays
ValueError: Schema and number of arrays unequal
```

**Desktop (please complete the following information):**
 - Windows 10

**Comment by xushiyan** [comment]
@hsduan Would you be able to zip s3://my-bucket/sandbox/daft_hudi/.hoodie and attach it here? or s3://my-bucket/sandbox/daft_hudi/.hoodie/hoodie.properties ? the former would be more helpful

**Comment by hsduan** [comment]
@xushiyan is there a way to pass the file to you directly without posting it here? I'm not clear what user information may be in that directory and thus don't know if it is a good idea to post here.

**Comment by hsduan** [comment]
This is hoodie.properties: [hoodie.properties.zip](https://github.com/user-attachments/files/16401434/hoodie.properties.zip)

**Comment by xushiyan** [comment]
@hsduan .hoodie folder only contains metadata no sensitive info or actual data. You may also send the zip file to me directly xushiyan@apache.org

**Comment by xushiyan** [comment]
> @xushiyan I've zipped s3://my-bucket/sandbox/daft_hudi/.hoodie and sent it to your email. Thanks!

@hsduan looks like apache email blocks attachments.. could you send to raymond@onehouse.ai instead pls? thanks

**Comment by hsduan** [comment]
@xushiyan sent.
