### ISSUE TITLE
Reads of extremely large pages from Parquet fail with "Operation would exceed memory use threshold"

### ISSUE THREAD

**Issue by MisterKloudy** [Eventual-Inc/Daft#3007]
### Describe the bug

```
Traceback (most recent call last):
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/working_dir_files/_ray_pkg_5cf0d8f0f4230160/random_task.py", line 109, in <module>
    main()
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/working_dir_files/_ray_pkg_5cf0d8f0f4230160/random_task.py", line 30, in main
    df.into_partitions(1).write_parquet("/data/arxiv_research_code/")
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/api_annotations.py", line 26, in _wrap
    return timed_method(*args, **kwargs)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/analytics.py", line 198, in tracked_method
    return method(*args, **kwargs)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 554, in write_parquet
    write_df.collect()
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/api_annotations.py", line 26, in _wrap
    return timed_method(*args, **kwargs)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/analytics.py", line 198, in tracked_method
    return method(*args, **kwargs)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 2416, in collect
    dataframe_len = len(self._result)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 324, in __len__
    return sum(result.metadata().num_rows for result in self._results.values())
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 324, in <genexpr>
    return sum(result.metadata().num_rows for result in self._results.values())
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 1225, in metadata
    return self._metadatas.get_index(self._metadata_idx)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 1247, in get_index
    return self._get_metadatas()[key]
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 1243, in _get_metadatas
    self._metadatas = ray.get(self._ref)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2639, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DaftCoreException): [36mray::ReduceMerge-WriteFile [Stage:1]()[39m (pid=15965, ip=10.157.71.240)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 513, in reduce_pipeline
    return build_partitions(instruction_stack, partial_metadatas, *ray.get(inputs))
ray.exceptions.RayTaskError(DaftCoreException): [36mray::ScanWithTask [Stage:2]()[39m (pid=31117, ip=10.157.69.236)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/table/micropartition.py", line 364, in __reduce__
    return MicroPartition.from_pydict, ({name: self.get_column(name) for name in names},)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/table/micropartition.py", line 364, in <dictcomp>
    return MicroPartition.from_pydict, ({name: self.get_column(name) for name in names},)
  File "/tmp/ray/session_2024-09-29_14-48-32_270438_4696/runtime_resources/pip/d41a075b3fe5ff91ac6a6ade853b52f399540f57/virtualenv/lib/python3.9/site-packages/daft/table/micropartition.py", line 45, in get_column
    return Series._from_pyseries(self._micropartition.get_column(name))
daft.exceptions.DaftCoreException: DaftError::ArrowError External format error: Operation would exceed memory use threshold
```

### To Reproduce

```
import daft

def main():
    daft.context.set_runner_ray()
    df = daft.read_parquet('hf://datasets/AlgorithmicResearchGroup/arxiv_research_code/')
    df.repartition(1).write_parquet("/tmp/ray/llm_algo/data/arxiv_research_code/")

if __name__ == "__main__":
    main()
```
on Ray

### Expected behavior

Expected successful writes with bigger worker nodes and bigger memory.
Entire dataset is 9GB in parquet.
Pods of 20 cores and 200GB memory were available but tasks are assigned with single cores.
Perhaps if it fails it should retry with more cores? Or allow specification of the required memory like UDFs?

### Component(s)

Ray Runner

**Comment by jaychia** [comment]
Thanks @MisterKloudy 

I think this might actually just be because we we parse parquet data as 32 bit offsets instead of 64...

We'll take a look to see if this is a quick fix on our end

**Comment by jaychia** [comment]
Interestingly, this seems to be an issue because we have a safeguard in a bunch of places in our code (to avoid zip-bomb explosions of data) when reading data from Parquet:

<img width="384" alt="image" src="https://github.com/user-attachments/assets/1fa0f24f-8fdb-4fe1-9ddb-73534a5b9abd">

It's a safeguard, but maybe we need a better strategy here.

**Comment by samster25** [comment]
Ah, maybe we should expose `max_page_size` to the user as a kwarg or execution config?

**Comment by MisterKloudy** [comment]
Sounds promising! I would though need more explanations in the docs on what `max_page_size` is and how it works 😅 and also what's the consequences of unleashing a zip bomb? 

This dataset is so small I wouldn't have imagined I would have needed to tweak anything to read it though. 

Maybe some kind of dataset profiler function would solve some of these problems whereby the data requires some special treatment.

**Comment by jaychia** [comment]
So imagine if your parquet data contains 100 quadrillion strings "a", but it was encoded as: "a"100quadrillion

Naively reading all that into memory as 100 quadrillion strings would explode the machine 😭

That's why we have a sanity guard here to prevent these kinds of problems. We can either increase the default (which might be reasonable given the type of data we work with) or make it configurable.

**Comment by MisterKloudy** [comment]
Makes sense! I wonder if seeing OOM might have been more decipherable haha but another idea I've been wondering about was if it was possible to scale the guard together with the size of the machine. Then it would be a true guard instead of an arbitrary one.

**Comment by omkar-foss** [comment]
Yes it would be great to have the `max_page_size` configurable via execution config or so, while defaulting it to a percentage of system memory, much like JVM's heap size property `MaxRAMPercentage` that defaults to 25% of system memory and is configurable via `-XX:MaxRAMPercentage=` option.
