### ISSUE TITLE
Missing support for Float16 type `pyarrow.FixedShapeTensorArray` or `ray.air.util.tensor_extensions.arrow.ArrowTensorArray` from parquet/pyarrow sources

### ISSUE THREAD

**Issue by NellyWhads** [Eventual-Inc/Daft#3126]
### Describe the bug

When attempting to load a pyarrow table with a `FixedShapeTensorArray` or `ArrowTensorArray` column, the table cannot be loaded as a daft dataframe. This issue raises a more clear error when using the `from_array` api, as opposed to the `read_parquet` api.

Looking at the daft code, it looks like the float16 type is not fully implemented.

### To Reproduce

0. Imports
```python
import numpy as np
import pyarrow as pa
import daft
from pprint import pprint
```

2. Create Tensor Array

```python
tensors = np.arange(3 * 10 * 10).reshape((3, 10, 10)).astype(np.float16)
pprint(f"{tensors.shape=}, {tensors.dtype=}")
tensor_array = pa.FixedShapeTensorArray.from_numpy_ndarray(tensors)
pprint(f"{tensor_array.type=}")
```

```
"tensors.shape=(3, 10, 10), tensors.dtype=dtype('float16')"
('tensor_array.type=FixedShapeTensorType(extension<arrow.fixed_shape_tensor[value_type=halffloat, shape=[10,10], permutation=[0,1]]>)')
```

3. Create table
```python
ids = pa.array([np.float16(1), np.float16(2), np.float16(3)], type=pa.float16())
table = pa.Table.from_arrays([ids, tensor_array], names=["id", "tensor"])
pprint(table.schema)
```

```
id: halffloat
tensor: extension<arrow.fixed_shape_tensor[value_type=halffloat, shape=[10,10], permutation=[0,1]]>
```

4. Convert to Daft DataFrame
```python
df = daft.from_arrow(table)
df.schema()
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[34], [line 1](vscode-notebook-cell:?execution_count=34&line=1)
----> [1](vscode-notebook-cell:?execution_count=34&line=1) df = daft.from_arrow(table)
      [2](vscode-notebook-cell:?execution_count=34&line=2) df.schema()

    [... skipping hidden 2 frame]

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:115, in from_arrow(data)
     [85](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:85) """Creates a DataFrame from a pyarrow Table.
     [86](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:86) 
     [87](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:87) Example:
   (...)
    [111](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:111)     DataFrame: DataFrame created from the provided pyarrow Table.
    [112](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:112) """
    [113](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:113) from daft import DataFrame
--> [115](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:115) return DataFrame._from_arrow(data)

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461, in DataFrame._from_arrow(cls, data)
    [459](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:459) if not isinstance(data, list):
    [460](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:460)     data = [data]
--> [461](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461) data_micropartitions = [MicroPartition.from_arrow(table) for table in data]
    [462](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:462) return cls._from_tables(*data_micropartitions)

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461, in <listcomp>(.0)
...
    [326](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/datatype.py:326)     if not isinstance(shape, tuple) or not shape or any(not isinstance(n, int) for n in shape):
    [327](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/datatype.py:327)         raise ValueError("Tensor shape must be a non-empty tuple of ints, but got: ", shape)
--> [328](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/datatype.py:328) return cls._from_pydatatype(PyDataType.tensor(dtype._dtype, shape))

ValueError: The data type for a tensor column must be numeric, but got: Python
```

When using `ray.air.util.tensor_extensions.arrow.ArrowTensorArray` instead in step 2, the error in step 4 looks like:
```
thread '<unnamed>' panicked at src/daft-schema/src/dtype.rs:720:18:
DataType :Float16 is not supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[38], [line 1](vscode-notebook-cell:?execution_count=38&line=1)
----> [1](vscode-notebook-cell:?execution_count=38&line=1) df = daft.from_arrow(table)
      [2](vscode-notebook-cell:?execution_count=38&line=2) df.schema()

    [... skipping hidden 2 frame]

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:115, in from_arrow(data)
     [85](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:85) """Creates a DataFrame from a pyarrow Table.
     [86](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:86) 
     [87](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:87) Example:
   (...)
    [111](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:111)     DataFrame: DataFrame created from the provided pyarrow Table.
    [112](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:112) """
    [113](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:113) from daft import DataFrame
--> [115](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/convert.py:115) return DataFrame._from_arrow(data)

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461, in DataFrame._from_arrow(cls, data)
    [459](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:459) if not isinstance(data, list):
    [460](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:460)     data = [data]
--> [461](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461) data_micropartitions = [MicroPartition.from_arrow(table) for table in data]
    [462](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:462) return cls._from_tables(*data_micropartitions)

File ~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/dataframe/dataframe.py:461, in <listcomp>(.0)
...
---> [49](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/series.py:49)         pys = PySeries.from_arrow(name, array)
     [50](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/series.py:50)         return Series._from_pyseries(pys)
     [51](https://file+.vscode-resource.vscode-cdn.net/Users/neil.wadhvana/workspaces/main/torc-robotics/pytorc/projects/next_gen_data/next_gen_data/~/.pyenv/versions/next_gen_data_38/lib/python3.8/site-packages/daft/series.py:51) elif isinstance(array, pa.ChunkedArray):

PanicException: DataType :Float16 is not supported
```

### Expected behavior

Evaluating all of the numeric numpy array dtypes, `float16` is the only one which doesn't work. The expectation is that this would also convert successfully.

<details><summary>Code</summary>
<p>

```python
from pprint import pprint
from typing import Union

import daft
import numpy as np
import pyarrow as pa
import ray
from ray.air.util.tensor_extensions.arrow import ArrowTensorArray

# From the numpy implementation in numpy/__init__.pyi - common numeric types for arrays
uint_types = [np.uint8, np.uint16, np.uint32, np.uint64]
int_types = [np.int8, np.int16, np.int32, np.int64]
float_types = [np.float16, np.float32, np.float64]


def create_pa_tensor_array(np_dtype: np.generic) -> pa.FixedShapeTensorArray:
    tensors = np.arange(3 * 10 * 10).reshape((3, 10, 10)).astype(np_dtype)
    # pprint(f"{tensors.shape=}, {tensors.dtype=}")
    tensor_array = pa.FixedShapeTensorArray.from_numpy_ndarray(tensors)
    # pprint(f"{tensor_array.type=}")
    return tensor_array


def create_ray_tensor_array(np_dtype: np.generic) -> ArrowTensorArray:
    tensors = np.arange(3 * 10 * 10).reshape((3, 10, 10)).astype(np_dtype)
    # pprint(f"{tensors.shape=}, {tensors.dtype=}")
    tensor_array = ArrowTensorArray.from_numpy(tensors)
    # pprint(f"{tensor_array.type=}")
    return tensor_array


def create_table(tensor_array: Union[pa.FixedShapeTensorArray, ArrowTensorArray]) -> pa.Table:
    ids = pa.array([np.float16(1), np.float16(2), np.float16(3)], type=pa.float16())
    table = pa.Table.from_arrays([ids, tensor_array], names=["id", "tensor"])
    # pprint(table.schema)
    return table


def try_convert_table(table: pa.Table) -> daft.DataFrame:
    try:
        df = daft.from_arrow(table)
        # pprint(df.schema())
        return df
    except BaseException as e:
        pprint(f"Exception: {e}")


if __name__ == "__main__":
    pprint(f"{daft.__version__=}")
    pprint(f"{pa.__version__=}")
    pprint(f"{np.__version__=}")
    pprint(f"{ray.__version__=}")
    pprint("")

    pprint("Pyarrow FixedShapeTensorArray")
    for type_ in [*int_types, *uint_types, *float_types]:
        pprint(f"numpy type: {type_}")
        array = create_pa_tensor_array(type_)
        table = create_table(array)
        df = try_convert_table(table)
        pprint("Converted")

    pprint("")
    pprint("Ray ArrowTensorArray")
    for type_ in [*int_types, *uint_types, *float_types]:
        pprint(f"numpy type: {type_}")
        array = create_ray_tensor_array(type_)
        table = create_table(array)
        df = try_convert_table(table)
        pprint("Converted")
```

</p>
</details> 

<details><summary>Output</summary>
<p>

```
"daft.__version__='0.3.9'"
"pa.__version__='17.0.0'"
"np.__version__='1.24.4'"
"ray.__version__='2.10.0'"
''
'Pyarrow FixedShapeTensorArray'
"numpy type: <class 'numpy.int8'>"
'Converted'
"numpy type: <class 'numpy.int16'>"
'Converted'
"numpy type: <class 'numpy.int32'>"
'Converted'
"numpy type: <class 'numpy.int64'>"
'Converted'
"numpy type: <class 'numpy.uint8'>"
'Converted'
"numpy type: <class 'numpy.uint16'>"
'Converted'
"numpy type: <class 'numpy.uint32'>"
'Converted'
"numpy type: <class 'numpy.uint64'>"
'Converted'
"numpy type: <class 'numpy.float16'>"
'Exception: The data type for a tensor column must be numeric, but got: Python'
'Converted'
"numpy type: <class 'numpy.float32'>"
'Converted'
"numpy type: <class 'numpy.float64'>"
'Converted'
''
'Ray ArrowTensorArray'
"numpy type: <class 'numpy.int8'>"
'Converted'
"numpy type: <class 'numpy.int16'>"
'Converted'
"numpy type: <class 'numpy.int32'>"
'Converted'
"numpy type: <class 'numpy.int64'>"
'Converted'
"numpy type: <class 'numpy.uint8'>"
'Converted'
"numpy type: <class 'numpy.uint16'>"
'Converted'
"numpy type: <class 'numpy.uint32'>"
'Converted'
"numpy type: <class 'numpy.uint64'>"
'Converted'
"numpy type: <class 'numpy.float16'>"
thread '<unnamed>' panicked at src/daft-schema/src/dtype.rs:720:18:
DataType :Float16 is not supported
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
'Exception: DataType :Float16 is not supported'
'Converted'
"numpy type: <class 'numpy.float32'>"
'Converted'
"numpy type: <class 'numpy.float64'>"
'Converted'
```

</p>
</details> 

### Component(s)

Parquet, Other

### Additional context

As per contributing.md:

Operating system - macOS Sonoma 14.5
Runner that your code is using - python

**Comment by NellyWhads** [comment]
More info:

When using `from_table()`, columns with `pa.float16` scalar (not array) data are loaded successfully, however, they cause an error in `read_parquet()`.

**Comment by samster25** [comment]
hi @NellyWhads!

Today we don't have great support for float16. If this is a blocker in your workload, we could bump up the priority.

The key thing would be to extend our current numerical kernels to also support the half type

**Comment by NellyWhads** [comment]
Hey @samster25 - I can put off some of the immediacy by relying on float32 for now - I'm working with a rather large datalake and roughly 1/3 of the float types are float16.

If there's a reasonable way to push this forward, I would deeply appreciate it.

**Comment by mfine15** [comment]
This is definitely a blocker in our workload -- we'd love if you could implement float16 support!

**Comment by rchowell** [comment]
Related #2889
